# 
rel:
	@cd hifb;   make
	@cd vio;    make
	@cd venc;   make
	@cd vdec;   make
	@cd region;    make
	@cd vda;    make
	@cd audio;  make
	@cd tde;    make
	@cd it;    make
	@cd ive;    make

clean:
	@cd hifb;   make clean
	@cd vio;    make clean
	@cd venc;   make clean
	@cd vdec;   make clean
	@cd region; make clean
	@cd vda;    make clean
	@cd audio;  make clean
	@cd tde; make clean
	@cd it; make clean
	@cd ive; make clean

cleanall:
	@cd hifb;   make clean;   make cleanstream
	@cd vio;    make clean;   make cleanstream
	@cd venc;   make clean;   make cleanstream
	@cd vdec;   make clean;   make cleanstream
	@cd region;    make clean;   make cleanstream
	@cd vda;    make clean;   make cleanstream
	@cd audio;  make clean;   make cleanstream
	@cd tde; make clean
	@cd it; make clean
	@cd ive; make clean

